var simplemaps_countrymap_mapdata = {
  main_settings: {
    width: "auto",
    background_color: "#FFFFFF",
    background_transparent: "yes",
    border_color: "#ffffff",
    pop_ups: "detect",
    state_color: "#CBD5E1",
    state_hover_color: "#3B729F",
    state_url: "",
    border_size: 1.5,
    all_states_inactive: "no",
    location_color: "#FF0067",
    location_type: "square",
    location_size: 25,
    all_locations_inactive: "no",
    label_color: "#ffffff",
    label_size: 16,
    label_font: "Arial",
    hide_labels: "no",

    zoom: "no",
    manual_zoom: "no",

    div: "map",
    auto_load: "yes",
    url_new_tab: "no",
    callback: "yes",
  },
  state_specific: {
    MM01: { name: "Sagaing" },
    MM02: { name: "Bago" },
    MM03: { name: "Magway" },
    MM04: { name: "Mandalay" },
    MM05: { name: "Tanintharyi" },
    MM06: { name: "Yangon" },
    MM07: { name: "Ayeyarwady" },
    MM11: { name: "Kachin" },
    MM12: { name: "Kayah" },
    MM13: { name: "Kayin" },
    MM14: { name: "Chin" },
    MM15: { name: "Mon" },
    MM16: { name: "Rakhine" },
    MM17: { name: "Shan" },
  },
  labels: {},
};
